[package]
name = "ssz-rs"
version = "0.8.0"
rust-version = "1.60"
authors = ["Alex Stokes <r.alex.stokes@gmail.com>"]
edition = "2021"
license = "MIT"
readme = "../README.md"
description = "ethereum's simple serialize"
repository = "https://github.com/ralexstokes/ssz-rs"
exclude = [
    "scripts",
    "tests/data",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["serde", "std"]
std = [
    "bitvec/std",
    "sha2/std",
    "num-bigint/std",
    "serde/std"
]
serde = ["dep:serde", "dep:hex"]

[dependencies]
thiserror = "1.0.25"
bitvec = { version = "1.0.0", default-features = false, features=["alloc"]}
ssz-rs-derive = { path = "../ssz-rs-derive"}
sha2 = { version ="0.9.8", default-features = false}
lazy_static = { version = "1.4.0", features = ["spin_no_std"]}
serde = { version = "1.0", default-features = false, features = ["alloc", "derive"], optional = true }
hex = {version = "0.4.3", default-features = false, features = ["alloc"], optional = true }
num-bigint = { version ="0.4.3", default-features = false}

[dev-dependencies]
hex-literal = "0.3.3"
snap = "1.0"
project-root = "0.2.2"
serde_json = "1.0.81"
